In [1]:
import numpy as np

In [23]:
def info_array(a):
    print("Dimension - ",a.ndim)
    print("shape - ", a.shape)
    print("size(No. Of Elements) - ",a.size)
    print("Datatype - ",a.dtype)

In [4]:
arr1 = np.arange(12)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [6]:
arr1.ndim

1

In [7]:
arr1.shape

(12,)

In [8]:
arr1.dtype

dtype('int32')

In [9]:
arr1.size

12

In [14]:
arr2 = np.linspace(1,2,34)
arr2

array([1.        , 1.03030303, 1.06060606, 1.09090909, 1.12121212,
       1.15151515, 1.18181818, 1.21212121, 1.24242424, 1.27272727,
       1.3030303 , 1.33333333, 1.36363636, 1.39393939, 1.42424242,
       1.45454545, 1.48484848, 1.51515152, 1.54545455, 1.57575758,
       1.60606061, 1.63636364, 1.66666667, 1.6969697 , 1.72727273,
       1.75757576, 1.78787879, 1.81818182, 1.84848485, 1.87878788,
       1.90909091, 1.93939394, 1.96969697, 2.        ])

In [15]:
arr3 = np.linspace(10,45,6)
arr3

array([10., 17., 24., 31., 38., 45.])

In [16]:
arr4 = np.linspace(1,9,4)
arr4

array([1.        , 3.66666667, 6.33333333, 9.        ])

In [17]:
arr5 = np.linspace(1,2,125)
arr5

array([1.        , 1.00806452, 1.01612903, 1.02419355, 1.03225806,
       1.04032258, 1.0483871 , 1.05645161, 1.06451613, 1.07258065,
       1.08064516, 1.08870968, 1.09677419, 1.10483871, 1.11290323,
       1.12096774, 1.12903226, 1.13709677, 1.14516129, 1.15322581,
       1.16129032, 1.16935484, 1.17741935, 1.18548387, 1.19354839,
       1.2016129 , 1.20967742, 1.21774194, 1.22580645, 1.23387097,
       1.24193548, 1.25      , 1.25806452, 1.26612903, 1.27419355,
       1.28225806, 1.29032258, 1.2983871 , 1.30645161, 1.31451613,
       1.32258065, 1.33064516, 1.33870968, 1.34677419, 1.35483871,
       1.36290323, 1.37096774, 1.37903226, 1.38709677, 1.39516129,
       1.40322581, 1.41129032, 1.41935484, 1.42741935, 1.43548387,
       1.44354839, 1.4516129 , 1.45967742, 1.46774194, 1.47580645,
       1.48387097, 1.49193548, 1.5       , 1.50806452, 1.51612903,
       1.52419355, 1.53225806, 1.54032258, 1.5483871 , 1.55645161,
       1.56451613, 1.57258065, 1.58064516, 1.58870968, 1.59677

In [24]:
info_array(arr5)

Dimension -  1
shape -  (125,)
size(No. Of Elements) -  125
Datatype -  float64


In [38]:
arr6 = np.linspace(1,24,24)
arr6

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24.])

In [39]:
arr6.shape

(24,)

In [40]:
arr6.reshape(4,6)

array([[ 1.,  2.,  3.,  4.,  5.,  6.],
       [ 7.,  8.,  9., 10., 11., 12.],
       [13., 14., 15., 16., 17., 18.],
       [19., 20., 21., 22., 23., 24.]])

In [42]:
arr8 = np.arange(1,7).reshape(2,3)
arr8

array([[1, 2, 3],
       [4, 5, 6]])

In [43]:
arr9 = np.arange(7,13).reshape(2,3)
arr9

array([[ 7,  8,  9],
       [10, 11, 12]])

In [44]:
np.concatenate([arr8,arr9])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [45]:
np.concatenate([arr8,arr9],axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [ ]:
### hstack(Horizontal Stack):-  used to stack array in horizontal mannaer- column join
### vstack(Vertical Stack):- used to stack array in vertical mannaer- horizontal join